// import css var system
import "./vars.css"
import "./palette.css"
import "./derived.css"
// import comp styles
import "./base.css"
import "./button.css"
import "./frame.css"
import "./cells.css"
import "./jacket.css"
import "./tooltip.css"
import "./preview.css"
import "./background.css"
import "./carousel.css"
import "./decor.css"
import "./note.css"
import "./photo.css"
import "./picture.css"
import "./view.css"
// transition style for vue
import "./transition.css"
